#ifndef SAMPLERSTATE_HEADER
#define SAMPLERSTATE_HEADER

SamplerState gSamWrapLinear;
SamplerState gSamWrapLinearPoint;
SamplerState gSamWrapAnisotropic;
SamplerState gSamClampAnisotropic;
SamplerState gSamClampLinearPoint;
SamplerState gSamClampLinear;
SamplerState gSamClampPoint;
SamplerState gSamMirrorLinear;
SamplerState gSamBorderLinear;
SamplerState gSamBorderLinearPoint;
SamplerComparisonState gSamBorderComparisonLinearPoint;

#endif